version: '3'
services:
  activemq:
    container_name: activemq
    image: bobcrutchley/activemq
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
    - ./data/db:/data/db
  account-api:
    container_name: account-api
    build:
      context: Account-Api
      args:
      - artifact_id=account-api
      - version=1.0.0
  account-number-generator:
    container_name: account-number-generator
    build:
      context: Account-Number-Generator
      args:
      - artifact_id=account-number-generator
      - version=1.0.0
  account-prize-generator:
    container_name: account-prize-generator
    build:
      context: Account-Prize-Generator
      args:
      - artifact_id=account-prize-generator
      - version=1.0.0
  account-consumer:
    container_name: account-consumer
    build:
      context: Account-Consumer
      args:
      - artifact_id=account-consumer
      - version=1.0.0
  account-front-end:
    container_name: account-front-end
    build:
      context: Account-Front-End
      args:
      - artifact_id=account-front-end
      - version=1.0.0
    ports:
    - 80:3000